# Generated by Django 5.2.8 on 2025-11-21 00:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Full name of the user', max_length=255)),
                ('household_size', models.PositiveIntegerField(default=1, help_text='Number of people in household')),
                ('dietary_preferences', models.CharField(choices=[('none', 'No specific diet'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('pescatarian', 'Pescatarian'), ('gluten-free', 'Gluten-Free'), ('keto', 'Keto'), ('other', 'Other')], default='none', help_text='Dietary preferences or restrictions', max_length=50)),
                ('budget_range', models.CharField(choices=[('low', 'Low ($0-50/week)'), ('medium', 'Medium ($50-100/week)'), ('high', 'High ($100+/week)')], default='medium', help_text='Weekly food budget range', max_length=20)),
                ('location', models.CharField(blank=True, help_text='Location (city, state, country) for future local features', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
