# Generated by Django 5.2.8 on 2025-11-21 02:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_fooditem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('context', models.JSONField(default=dict, help_text='Session context (user preferences, recent activity, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Session',
                'verbose_name_plural': 'Chat Sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(default=dict, help_text='Additional message metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_analytics.chatsession')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['session', 'created_at'], name='ai_analytic_session_32a9c5_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConsumptionPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_type', models.CharField(choices=[('weekly_trend', 'Weekly Trend'), ('category_imbalance', 'Category Imbalance'), ('over_consumption', 'Over Consumption'), ('under_consumption', 'Under Consumption'), ('waste_risk', 'Waste Risk')], max_length=50)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('detected_date', models.DateField(auto_now_add=True)),
                ('data', models.JSONField(default=dict, help_text='Additional pattern data in JSON format')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumption_patterns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consumption Pattern',
                'verbose_name_plural': 'Consumption Patterns',
                'ordering': ['-detected_date', '-severity'],
                'indexes': [models.Index(fields=['user', '-detected_date'], name='ai_analytic_user_id_65e90a_idx'), models.Index(fields=['pattern_type'], name='ai_analytic_pattern_8ccad7_idx')],
            },
        ),
        migrations.CreateModel(
            name='NutrientGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nutrient_name', models.CharField(help_text='e.g., Vitamin C, Iron, Protein', max_length=100)),
                ('current_level', models.DecimalField(decimal_places=2, help_text='Current estimated level', max_digits=10)),
                ('recommended_level', models.DecimalField(decimal_places=2, help_text='Recommended level', max_digits=10)),
                ('gap_percentage', models.DecimalField(decimal_places=2, help_text='Gap percentage (0-100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('suggested_foods', models.JSONField(default=list, help_text='List of foods that can fill this gap')),
                ('detected_date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrient_gaps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nutrient Gap',
                'verbose_name_plural': 'Nutrient Gaps',
                'ordering': ['-gap_percentage', '-detected_date'],
                'indexes': [models.Index(fields=['user', '-gap_percentage'], name='ai_analytic_user_id_2e264f_idx')],
            },
        ),
        migrations.CreateModel(
            name='SDGImpactScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.DecimalField(decimal_places=2, help_text='Overall SDG score (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('waste_reduction_score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('nutrition_score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('sustainability_score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('week_start_date', models.DateField(help_text='Start date of the week this score represents')),
                ('insights', models.JSONField(default=dict, help_text='AI-generated insights')),
                ('actionable_steps', models.JSONField(default=list, help_text='List of actionable steps to improve score')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdg_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SDG Impact Score',
                'verbose_name_plural': 'SDG Impact Scores',
                'ordering': ['-week_start_date', '-created_at'],
                'indexes': [models.Index(fields=['user', '-week_start_date'], name='ai_analytic_user_id_29b6ea_idx')],
                'unique_together': {('user', 'week_start_date')},
            },
        ),
        migrations.CreateModel(
            name='WastePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=50)),
                ('predicted_waste_probability', models.DecimalField(decimal_places=2, help_text='Probability of waste (0-100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('predicted_waste_date', models.DateField(help_text='Predicted date when item will be wasted')),
                ('reasoning', models.TextField(help_text='AI reasoning for the prediction')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waste_predictions', to='inventory.inventoryitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Waste Prediction',
                'verbose_name_plural': 'Waste Predictions',
                'ordering': ['-predicted_waste_probability', 'predicted_waste_date'],
                'indexes': [models.Index(fields=['user', '-predicted_waste_probability'], name='ai_analytic_user_id_67dae9_idx'), models.Index(fields=['predicted_waste_date'], name='ai_analytic_predict_1bf150_idx')],
            },
        ),
    ]
