# Generated by Django 5.2.8 on 2025-11-21 00:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(help_text='Name of the food item', max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Current quantity', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(choices=[('kg', 'Kilogram (kg)'), ('g', 'Gram (g)'), ('lb', 'Pound (lb)'), ('oz', 'Ounce (oz)'), ('l', 'Liter (l)'), ('ml', 'Milliliter (ml)'), ('cup', 'Cup'), ('piece', 'Piece'), ('pack', 'Pack')], default='piece', max_length=20)),
                ('category', models.CharField(choices=[('vegetable', 'Vegetable'), ('fruit', 'Fruit'), ('dairy', 'Dairy'), ('meat', 'Meat'), ('grain', 'Grain'), ('beverage', 'Beverage'), ('snack', 'Snack'), ('frozen', 'Frozen'), ('canned', 'Canned'), ('other', 'Other')], default='other', max_length=50)),
                ('purchase_date', models.DateField(help_text='Date when the item was purchased')),
                ('expiration_date', models.DateField(blank=True, help_text='Expected expiration date (optional)', null=True)),
                ('status', models.CharField(choices=[('fresh', 'Fresh'), ('expiring_soon', 'Expiring Soon'), ('expired', 'Expired'), ('consumed', 'Consumed')], default='fresh', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inventory Item',
                'verbose_name_plural': 'Inventory Items',
                'ordering': ['expiration_date', 'item_name'],
                'indexes': [models.Index(fields=['user', 'status'], name='inventory_i_user_id_7f2f20_idx'), models.Index(fields=['expiration_date'], name='inventory_i_expirat_6ff874_idx'), models.Index(fields=['category'], name='inventory_i_categor_fe6a79_idx')],
            },
        ),
    ]
