# Generated by Django 5.2.8 on 2025-11-21 00:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the food item', max_length=255, unique=True)),
                ('category', models.CharField(choices=[('vegetable', 'Vegetable'), ('fruit', 'Fruit'), ('dairy', 'Dairy'), ('meat', 'Meat'), ('grain', 'Grain'), ('beverage', 'Beverage'), ('snack', 'Snack'), ('frozen', 'Frozen'), ('canned', 'Canned'), ('spice', 'Spice'), ('other', 'Other')], help_text='Food category', max_length=50)),
                ('typical_expiration_days', models.PositiveIntegerField(blank=True, help_text='Typical expiration period in days', null=True)),
                ('sample_cost_per_unit', models.DecimalField(blank=True, decimal_places=2, help_text='Sample cost per unit (for reference)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(choices=[('kg', 'Kilogram (kg)'), ('g', 'Gram (g)'), ('lb', 'Pound (lb)'), ('oz', 'Ounce (oz)'), ('l', 'Liter (l)'), ('ml', 'Milliliter (ml)'), ('cup', 'Cup'), ('piece', 'Piece'), ('pack', 'Pack'), ('bunch', 'Bunch')], default='piece', help_text='Unit of measurement', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Description of the food item', null=True)),
                ('storage_tips', models.TextField(blank=True, help_text='Tips for storing this item', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Food Item',
                'verbose_name_plural': 'Food Items',
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['category'], name='inventory_f_categor_89de93_idx'), models.Index(fields=['name'], name='inventory_f_name_7fa6f7_idx')],
            },
        ),
    ]
