# Generated by Django 5.2.8 on 2025-11-21 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_fooditem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpirationEmailNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_date', models.DateField(auto_now_add=True, help_text='Date when email was sent')),
                ('days_before_expiry', models.IntegerField(help_text='Days before expiration when email was sent')),
                ('email_sent', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_notifications', to='inventory.inventoryitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expiration_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expiration Email Notification',
                'verbose_name_plural': 'Expiration Email Notifications',
                'indexes': [models.Index(fields=['user', 'sent_date'], name='inventory_e_user_id_fa4c4b_idx'), models.Index(fields=['inventory_item', 'days_before_expiry'], name='inventory_e_invento_7685a9_idx')],
                'unique_together': {('inventory_item', 'days_before_expiry')},
            },
        ),
    ]
