# Generated by Django 5.2.8 on 2025-11-21 00:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(help_text='Name of the food item', max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity consumed', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(choices=[('kg', 'Kilogram (kg)'), ('g', 'Gram (g)'), ('lb', 'Pound (lb)'), ('oz', 'Ounce (oz)'), ('l', 'Liter (l)'), ('ml', 'Milliliter (ml)'), ('cup', 'Cup'), ('piece', 'Piece'), ('serving', 'Serving')], default='piece', max_length=20)),
                ('category', models.CharField(choices=[('vegetable', 'Vegetable'), ('fruit', 'Fruit'), ('dairy', 'Dairy'), ('meat', 'Meat'), ('grain', 'Grain'), ('beverage', 'Beverage'), ('snack', 'Snack'), ('other', 'Other')], default='other', max_length=50)),
                ('date_consumed', models.DateField(help_text='Date when the food was consumed')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the consumption', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Food Log',
                'verbose_name_plural': 'Food Logs',
                'ordering': ['-date_consumed', '-created_at'],
                'indexes': [models.Index(fields=['user', '-date_consumed'], name='logs_foodlo_user_id_3afff2_idx'), models.Index(fields=['category'], name='logs_foodlo_categor_c0677e_idx')],
            },
        ),
    ]
