# Generated by Django 5.2.8 on 2025-11-21 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the resource', max_length=255)),
                ('description', models.TextField(help_text='Description of the resource')),
                ('url', models.URLField(blank=True, help_text='URL to the resource (if applicable)', null=True)),
                ('category', models.CharField(choices=[('waste_reduction', 'Waste Reduction'), ('budget_tips', 'Budget Tips'), ('meal_planning', 'Meal Planning'), ('storage_tips', 'Storage Tips'), ('nutrition', 'Nutrition'), ('sustainability', 'Sustainability'), ('cooking_tips', 'Cooking Tips'), ('preservation', 'Food Preservation'), ('shopping', 'Smart Shopping'), ('other', 'Other')], help_text='Category of the resource', max_length=50)),
                ('resource_type', models.CharField(choices=[('article', 'Article'), ('video', 'Video'), ('guide', 'Guide'), ('tip', 'Tip'), ('recipe', 'Recipe'), ('tool', 'Tool'), ('website', 'Website')], default='article', help_text='Type of resource', max_length=20)),
                ('featured', models.BooleanField(default=False, help_text='Mark as featured resource')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
                'ordering': ['-featured', 'category', 'title'],
                'indexes': [models.Index(fields=['category'], name='resources_r_categor_8e2710_idx'), models.Index(fields=['resource_type'], name='resources_r_resourc_1a6f3f_idx'), models.Index(fields=['featured'], name='resources_r_feature_b91302_idx')],
            },
        ),
    ]
