# Generated by Django 5.2.8 on 2025-11-21 01:13

import django.core.validators
import django.db.models.deletion
import uploads.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_fooditem'),
        ('logs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload JPG or PNG image (max 10MB)', upload_to=uploads.models.upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('upload_type', models.CharField(choices=[('receipt', 'Receipt'), ('food_label', 'Food Label'), ('barcode', 'Barcode'), ('other', 'Other')], default='other', help_text='Type of upload', max_length=20)),
                ('title', models.CharField(blank=True, help_text='Optional title for the upload', max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='Optional description', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('associated_inventory', models.ForeignKey(blank=True, help_text='Associated inventory item (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to='inventory.inventoryitem')),
                ('associated_log', models.ForeignKey(blank=True, help_text='Associated food log (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to='logs.foodlog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Upload',
                'verbose_name_plural': 'Uploads',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='uploads_upl_user_id_a1664e_idx'), models.Index(fields=['upload_type'], name='uploads_upl_upload__5fac95_idx')],
            },
        ),
    ]
